# Generated by Django 3.2.2 on 2021-07-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('task_title', models.CharField(max_length=200)),
                ('task_desc', models.TextField()),
                ('task_pic', models.ImageField(upload_to='uploads/')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
